### PR TITLE
Merge States with master

### PR DESCRIPTION
**Pull request by brenapp**
Just to simplify

### CODE REVIEW

**Comment by ghost** [comment]
OK... I'd have left the branch jut to distinguish between them, but it's your repo. :smiley:

**Comment by brenapp** [comment]
I was having trouble pushing from my home computer, so I merged. If need be, I'll create a branch here and then push it.

**Comment by BenJetson** [comment]
Here's how you deal with branches via CLI. 

Clone the repo (if you haven't already)
`$ cd ~/Documents/GitHub/`
`$ git clone https://github.com/mannrobo/nothing_but_net-B`
`$ cd ./nothing_but_net-B`

Switch branches (this defaults to master for this repo, so you'll need to change):
`$ git checkout states`

Work on the code as necessary. Then, add the current directory and its children to be committed.
`$ git add .`
`$ git commit -m "insert a commit comment here"`

Push the code up. You'll need to authenticate, so have your credentials handy.
`$ git push`
`Enter username for github.com: *********`
`Enter password for *********@github.com: *********`
`Pushing... 100%` (or similar)

That should work. If it doesn't, you might be outside of the working directory or have an improper config value set. Be sure to use `git config --global` to set your `user.name` and `user.email` (Google this).

**Comment by brenapp** [comment]
I know how to merge, but it always takes forever

**Comment by BenJetson** [comment]
OK. Just trying to be helpful. :smiley: 
You and Mike both must watch your email like hawks or something... you both respond creepy fast whenever I send something. xD

**Comment by brenapp** [comment]
`>> <<`

**Comment by BenJetson** [comment]
Is that supposed to be a face or something?

**Comment by brenapp** [comment]
What do you mean?

**Comment by BenJetson** [comment]
image

**Comment by brenapp** [comment]
Must not have installed that keylogger very securely, your phone and/or computer must have a virus

**Comment by BenJetson** [comment]
Good luck with that.... it's darn hard to infect a Linux system you don't have root or physical access to. :stuck_out_tongue_closed_eyes: 

And yes, I did check the network administration logs/queue. And no, there wasn't any suspicious activity or any strange packets going through the hardware firewall either. xD

**Comment by brenapp** [comment]
I love that you actually checked the packets. Do you use WireShark?

**Comment by BenJetson** [comment]
Yup. I've got a rPi server that just kinda logs everything. :stuck_out_tongue:

**Comment by brenapp** [comment]
I lost my SD card on mine, so now I can't do anything :(

**Comment by BenJetson** [comment]
Buy a new one off Amazon, and then use this to keep it in. 
untitled
_*Not an actual official VRC product. Not for competition use._

**Comment by brenapp** [comment]
Is that supposed to say VEX competition, cause I just see some wierd black image
image

**Comment by BenJetson** [comment]
You might need to refresh. The first copy I uploaded had the image alpha layer disabled. It's much more funny when the transparency and layering translates correctly. xD

untitled
_*Not an actual official VRC product. Not for competition use._

**Comment by brenapp** [comment]
Well that makes much more sense, I thought your were just messing with me

**Pull request merged**
